Ben instructor search page
ucsb-cs156-s23/proj-courses-s23-7pm-1 pull request #36
Opened 2023-05-26 03:00 UTC by BenCrutt

Added form for instructor search, including dropdown selects for start quarter and end quarter. Then adds a text box to input the course instructor name for search. Currently, submit button does nothing, only frontend is built. Later hitting submit will show a table of courses that fall into the criteria given in the form. Resolves #2 

StoryBook:
Before(No Story File)
[After](https://ucsb-cs156-s23.github.io/proj-courses-s23-7pm-1/prs/36/storybook/?path=/docs/pages-courseinstructorindexpage--default)

Screenshot:
Before:
<img width="780" alt="Screenshot 2023-05-30 at 2 41 24 PM" src="https://github.com/ucsb-cs156-s23/proj-courses-s23-7pm-1/assets/122656360/f70deb51-a7a7-4cc6-a907-9a075318fc43">

After:
![Screenshot 2023-06-02 215639](https://github.com/ucsb-cs156-s23/proj-courses-s23-7pm-1/assets/122656360/e4453fec-f599-422a-8f65-1bd9b063387c)

2023-05-30 20:38 UTC, kdhulipala41 approved these changes, later dismissed
LGTM

2023-05-31 08:43 UTC, pconrad requested changes
A few small things to take a look at

2023-05-31 08:43 UTC, pconrad commented on frontend/src/main/components/Nav/AppNavbar.js
> +            </Nav>
If a dropdown has only one item in it, why even make it a drop down?  Why not just make it a link?

See https://react-bootstrap.github.io/docs/components/navbar for options and examples.

Also: see my feedback on #29 ... I'm just not sold on "Course Instructor" as a helpful label for this activity.  Maybe you can convince me, but I think "search by instructor" or even "Search by" with instructor / location / course number as the things in the dropdown menu would make much more sense...

2023-05-31 08:43 UTC, pconrad commented on frontend/src/main/components/BasicCourseSearch/InstructorCourseSearchForm.js
> +//import SingleLevelDropdown from "../Levels/SingleLevelDropdown";
We really try not to include commented out code in code that we are merging into main.

2023-05-31 08:43 UTC, pconrad commented on frontend/src/main/components/BasicCourseSearch/InstructorCourseSearchForm.js
> +  //const localCourseNumber = localStorage.getItem("InstructorCourseSearch.CourseNumber");
Do we need this commented out code?

2023-05-31 08:43 UTC, pconrad commented on frontend/src/main/components/BasicCourseSearch/InstructorCourseSearchForm.js
> +  //const [courseSuf, setCourseSuf] = useState("");
Do we need this?

2023-05-31 08:43 UTC, pconrad commented on frontend/src/main/components/BasicCourseSearch/InstructorCourseSearchForm.js
> +    //fetchJSON(event, { startQuarter, endQuarter, subject, courseNumber, courseSuf });
Do we need this commented out code

2023-06-03 21:22 UTC, pconrad requested changes
This mostly looks good! 

A few small things that should be changed (see below)

2023-06-03 21:22 UTC, pconrad commented on frontend/src/main/components/BasicCourseSearch/InstructorCourseSearchForm.js
> +  // Stryker enable OptionalChaining
Should be:
```suggestion
  // Stryker restore OptionalChaining
```

See: https://ucsb-cs156-s23.slack.com/archives/C050779M19P/p1685726928710669

2023-06-03 21:22 UTC, pconrad commented on frontend/src/main/components/BasicCourseSearch/InstructorCourseSearchForm.js
> +  // Stryker disable all : Stryker is testing by changing the padding to 0. But this is simply a visual optimization as it makes it look better
Please remove this.  We have a documented easy way to test this, so this is no longer an appropriate stryker exception.

See: https://ucsb-cs156.github.io/topics/stryker/stryker_html_attribute_surviving_mutants.html
See:

2023-06-05 01:02 UTC, pconrad approved these changes
LGTM!  Will test on staff-qa before merging

2023-06-06 00:01 UTC, merged