Ben instructor Instructor Text Box Updates
ucsb-cs156-s23/proj-courses-s23-7pm-1 pull request #56
Opened 2023-06-05 19:17 UTC by BenCrutt

This PR, adds functionality to the Course instructor text box on the course instructor search page.  It also makes it not case sensitive converting all uppercase letters to lowercase ones. Now, the form input will be ready for the backend to build the table. Resolves Issue #37 

Note the submit feature is not ready yet so upon pressing, it currently refreshes the page to lead to a better user experience. Getting the table set up is in the works and once ready the submit button will no longer refresh the page.

2023-06-06 07:41 UTC, b4k3s approved these changes, later dismissed
I reviewed your code and tested the functionality of qa deployment. Everything seems to work as you intended for this PR. LGTM.

2023-06-06 16:54 UTC, pconrad requested changes
There is a `// Stryker disable all` in front of the lines that use local storage, which is legit because we only recently learned how to mock local storage.

However, there isn't a matching `// Stryker restore all`, which means we are probably missing a lot of mutations that *should* have tests covering them.

When you put this in, you may get some mutation test failures, but those can be dealt with.

2023-06-06 16:54 UTC, pconrad commented on frontend/src/main/components/BasicCourseSearch/InstructorCourseSearchForm.js
>    // Stryker disable all : not sure how to test/mock local storage
These should be a `// Stryker restore all` somewhere ... maybe line 24?

2023-06-07 15:34 UTC, pconrad approved these changes
LGTM

2023-06-07 15:35 UTC, merged